default: &default
  host: ec2-23-21-246-11.compute-1.amazonaws.com
  username: vqyzkxkbruelso
  password: 346928028bb3ec0726f6817c15da9ecb24850bca616d40b53e4b6e1646cb2726
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Cocktail_Tour_development

test:
  <<: *default
  database: Cocktail_Tour_test

production:
  <<: *default
  database: Cocktail_Tour_production
  username: Cocktail_Tour
  password: <%= ENV['COCKTAIL_TOUR_PASSWORD'] %>