default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: trigun19731982
  host: localhost

development:
  <<: *default
  database: Cocktail_Tour_development

test:
  <<: *default
  database: Cocktail_Tour_test

production:
  <<: *default
  database: Cocktail_Tour_production
  username: Cocktail_Tour
  password: <%= ENV['COCKTAIL_TOUR_DATABASE_PASSWORD'] %>
